batch_size: 4
ckpt_freq: 100
data:
  eval_data: ''
  shuffle: false
  train_data: /sise/eliyanac-group/ron_al/talkbank_callhome_english/talkbank.jsonl
do_ckpt: true
do_eval: false
duration_sec: 100.0
eval_freq: 100
first_codebook_weight_multiplier: 100.0
full_finetuning: false
gradient_checkpointing: true
log_freq: 1
lora:
  enable: false
  ft_embed: false
  rank: 64
  scaling: 2.0
max_norm: 1.0
max_steps: 2000
moshi_paths:
  config_path: null
  hf_repo_id: kyutai/moshiko-pytorch-bf16
  mimi_path: null
  moshi_path: null
  tokenizer_path: null
num_ckpt_keep: 3
num_microbatches: 1
optim:
  lr: 2.0e-06
  pct_start: 0.05
  weight_decay: 0.1
overwrite_run_dir: true
param_dtype: bfloat16
run_dir: ./ttt_training_run1
save_adapters: true
seed: 0
text_padding_weight: 0.5
ttt:
  chunk_size: 256
  conv_kernel_size: 2
  enabled: true
  layer_frequency: 10
  learning_rate: 0.001
  start_layer: 10
  unfreeze_ttt_layers: false
wandb:
  key: ''
  offline: false
  project: moshi_in_place
  run_name: run1
world_size: 1
yarn:
  beta_fast: 32
  beta_slow: 1
  enabled: true
  mscale: 1.0
  mscale_all_dim: 0.0
  original_max_seq_len: 3000
  scale: 4.0
