# data
data:
  eval_data: '' # Optional Fill
  shuffle: false
  train_data: /sise/eliyanac-group/ron_al/talkbank_callhome_english/talkbank.jsonl

# model
moshi_paths: 
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"

full_finetuning: false # Use LoRA for memory efficiency
lora:
  enable: false # LoRA for base model + TTT for adaptive updates
  rank: 64  # Reduced from 128 for memory
  scaling: 2.
  ft_embed: false # Optional, set to True if you want to finetune the embedding layer

first_codebook_weight_multiplier: 100.
text_padding_weight: .5

# optim
duration_sec: 150
batch_size: 2  # Reduced from 16 for memory
max_steps: 2000
gradient_checkpointing: true  # Keep enabled for memory
optim:
  lr: 1e-2  # 10x higher to overpower weight decay (0.1) with tiny gradients (~1e-8)
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
do_eval: false
do_ckpt: true
ckpt_freq: 100


save_adapters: true # Save LoRA adapters

run_dir: "/sise/eliyanac-group/ron_al/ttt_training_run2"
overwrite_run_dir: true

# TTT Configuration - In-Place Test-Time Training
ttt:
  enabled: true
  layer_frequency: 10   # TTT every 10th layer (reduced from 6 for memory)
  start_layer: 10       # Start from layer 10 -> layers 10, 20, 30 (3 layers)
  chunk_size: 256       # 256 tokens per update
  learning_rate: 1e-4   # TTT learning rate
  conv_kernel_size: 2
  delta_clip_fro_norm: 100.0  # Clip deltas to prevent instability (1e-5 was too aggressive for norm~70 weights)

# YaRN (Context Window Extension) Configuration
yarn:
  enabled: true
  scale: 4.0  # Extend context by 4x (3000 -> 12000 tokens)
  original_max_seq_len: 3000  # Original Moshi context length
  beta_fast: 32  # Low frequency boundary (keep default)
  beta_slow: 1  # High frequency boundary (keep default)
  mscale: 1.0  # Attention scaling factor (keep default)
  mscale_all_dim: 0.0  # Additional scaling (keep default)

# This part is optional and can be kept commented out
wandb:
  project: "moshi_in_place" # your wandb project name
  run_name: "run2" # your wandb run name
  key: "" # your wandb api key
  offline: False
